name = "mindflow"
compatibility_date = "2025-05-23"
main = "workers-site/index.js"

[site]
bucket = "./"

# Configuração de domínio personalizado
[env.production]
routes = [{pattern = "mindflowdigital.com.br", custom_domain = true}]
